#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════
#  GYDS Chain — Lite Node  /  WireGuard Client Setup
#
#  Usage:
#    sudo bash setup-wireguard.sh [options]
#
#  Options:
#    --server-pubkey KEY        Server public key (required)
#    --server-endpoint IP:PORT  Server endpoint (required)
#    --client-vpn-ip IP/CIDR    This node's VPN IP (default: 10.8.0.5/32)
#    --vpn-subnet CIDR          VPN subnet (default: 10.8.0.0/24)
#    --wg-port PORT             WireGuard port (default: 51820)
#    --all-traffic              Route all traffic through VPN
#    --status | --down | --up | --show-pubkey
# ══════════════════════════════════════════════════════════════
set -euo pipefail

WG_IFACE="wg0"
WG_PORT="${WG_PORT:-51820}"
SERVER_PUBKEY="${SERVER_PUBKEY:-}"
SERVER_ENDPOINT="${SERVER_ENDPOINT:-}"
CLIENT_VPN_IP="${CLIENT_VPN_IP:-10.8.0.5/32}"
VPN_SUBNET="${VPN_SUBNET:-10.8.0.0/24}"
ALL_TRAFFIC=false
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

while [[ $# -gt 0 ]]; do
  case $1 in
    --server-pubkey)   SERVER_PUBKEY="$2";   shift 2 ;;
    --server-endpoint) SERVER_ENDPOINT="$2"; shift 2 ;;
    --client-vpn-ip)   CLIENT_VPN_IP="$2";   shift 2 ;;
    --vpn-subnet)      VPN_SUBNET="$2";      shift 2 ;;
    --wg-port)         WG_PORT="$2";         shift 2 ;;
    --all-traffic)     ALL_TRAFFIC=true;     shift ;;
    --status)   wg show; exit 0 ;;
    --down)     wg-quick down "$WG_IFACE" 2>/dev/null || true; echo "wg0 down"; exit 0 ;;
    --up)       wg-quick up   "$WG_IFACE" 2>/dev/null || true; echo "wg0 up";   exit 0 ;;
    --show-pubkey)
      [[ -f /etc/wireguard/privatekey ]] && wg pubkey < /etc/wireguard/privatekey || echo "Run setup first"
      exit 0 ;;
    *) shift ;;
  esac
done

log() { echo "[$(date '+%H:%M:%S')] $*"; }
err() { echo "[$(date '+%H:%M:%S')] ERROR: $*" >&2; exit 1; }

[[ $EUID -ne 0 ]] && err "Run as root: sudo bash $0"

[[ -z "$SERVER_PUBKEY"   ]] && read -rp "  Server public key: " SERVER_PUBKEY
[[ -z "$SERVER_ENDPOINT" ]] && read -rp "  Server endpoint (IP:PORT): " SERVER_ENDPOINT
[[ -z "$SERVER_PUBKEY"   ]] && err "Server public key required"
[[ -z "$SERVER_ENDPOINT" ]] && err "Server endpoint required"

log "Installing WireGuard..."
if ! command -v wg &>/dev/null; then
  command -v apt-get &>/dev/null && apt-get update -qq && apt-get install -y wireguard wireguard-tools resolvconf
  command -v dnf     &>/dev/null && dnf install -y wireguard-tools
  command -v yum     &>/dev/null && yum install -y epel-release && yum install -y wireguard-tools
fi

mkdir -p /etc/wireguard && chmod 700 /etc/wireguard
KEY_FILE="/etc/wireguard/privatekey"
PUB_FILE="/etc/wireguard/publickey"
if [[ ! -f "$KEY_FILE" ]]; then
  wg genkey | tee "$KEY_FILE" | wg pubkey > "$PUB_FILE"
  chmod 600 "$KEY_FILE"
else
  wg pubkey < "$KEY_FILE" > "$PUB_FILE"
fi
PRIVATE_KEY=$(cat "$KEY_FILE")
PUBLIC_KEY=$(cat "$PUB_FILE")

$ALL_TRAFFIC && ALLOWED_IPS="0.0.0.0/0, ::/0" || ALLOWED_IPS="$VPN_SUBNET"

CONF_FILE="/etc/wireguard/${WG_IFACE}.conf"
cat > "$CONF_FILE" <<WGCONF
# ── GYDS Chain Lite Node — WireGuard Client ─────────────────
# Generated by setup-wireguard.sh on $(date)

[Interface]
PrivateKey = ${PRIVATE_KEY}
Address    = ${CLIENT_VPN_IP}
ListenPort = ${WG_PORT}

PostUp   = ufw route allow in on ${WG_IFACE}
PostDown = ufw route delete allow in on ${WG_IFACE} 2>/dev/null; true

[Peer]
PublicKey  = ${SERVER_PUBKEY}
Endpoint   = ${SERVER_ENDPOINT}
AllowedIPs = ${ALLOWED_IPS}
PersistentKeepalive = 25
WGCONF
chmod 600 "$CONF_FILE"

mkdir -p "${SCRIPT_DIR}/wireguard"
cat > "${SCRIPT_DIR}/wireguard/wg0.conf.template" <<'TMPL'
# GYDS Lite Node — WireGuard Client template
[Interface]
PrivateKey = <GENERATED_ON_SERVER>
Address    = 10.8.0.5/32
ListenPort = 51820
PostUp   = ufw route allow in on wg0
PostDown = ufw route delete allow in on wg0 2>/dev/null; true
[Peer]
PublicKey  = <YOUR_SERVER_PUBLIC_KEY>
Endpoint   = <YOUR_SERVER_IP>:51820
AllowedIPs = 10.8.0.0/24
PersistentKeepalive = 25
TMPL

command -v ufw &>/dev/null && ufw allow "${WG_PORT}"/udp comment "WireGuard VPN"

systemctl enable "wg-quick@${WG_IFACE}"
wg-quick down "${WG_IFACE}" 2>/dev/null || true
wg-quick up   "${WG_IFACE}"
sleep 2 && wg show

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║      GYDS Lite Node — WireGuard Client Ready         ║"
echo "╚══════════════════════════════════════════════════════╝"
echo "  VPN IP  : ${CLIENT_VPN_IP}"
echo "  Server  : ${SERVER_ENDPOINT}"
echo ""
echo "  ┌─ ADD TO YOUR SERVER ───────────────────────────────┐"
echo "  │  [Peer]                                             │"
echo "  │  # GYDS litenode                                    │"
echo "  │  PublicKey  = ${PUBLIC_KEY}"
echo "  │  AllowedIPs = ${CLIENT_VPN_IP}              │"
echo "  └─────────────────────────────────────────────────────┘"
